spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:~/SHIPS;INIT=create schema if not exists SHIPS;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      autoCommit: false
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 150
      schema: SHIPS
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
    out-of-order: true
  rabbitmq:
    addresses: localhost:5672
    password: guest
    username: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 100

spaceship:
  openapi:
    external: com.meroz.spaceship
    internal: com.meroz.spaceship.internal
    title: ^project.name^
    version: ^project.version^
    description: ^project.description^
    terms-of-service: "www.google.com/terminos"
  security:
    aud: "Spaceship"

security:
  jwt:
    expiration-in-minutes: 10
    secret-key: cG9ycXVlIGVzdGFzIGJ1c2NhbmRvIGVzdG8/IGVzIHVuYSBwYXNzIHNlZ3VyYQ==