spring:
  application:
    name: Spaceship-api
  #  security:
  #    oauth2:
  #      resource server:
  #        jwt:
  #          key-uri: ${JWT_KEY_URI}
  config:
    activate:
      on-profile: ${PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
    hikari:
      autoCommit: false
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 150
      schema: spaceships
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
    out-of-order: true
    encoding: UTF-8
    execute-in-transaction: true
  rabbitmq:
    addresses: ${RABBIT_ADDRESS}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
    listener:
      simple:
        concurrency: 2
        max-concurrency: 100

spaceship:
  openapi:
    external: com.meroz.spaceship
    internal: com.meroz.spaceship.internal
    title: ^project.name^
    version: ^project.version^
    description: ^project.description^
    terms-of-service: "www.google.com/terminos"
  security:
    aud: ${SECURITY_AUD:Spaceship}

security:
  jwt:
    expiration-in-minutes: 10
    secret-key: cG9ycXVlIGVzdGFzIGJ1c2NhbmRvIGVzdG8/IGVzIHVuYSBwYXNzIHNlZ3VyYQ==